# Generated by Django 4.2 on 2025-09-29 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_permiso', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Permiso')),
                ('codigo_permiso', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('modulo', models.CharField(choices=[('PRODUCTOS', 'Productos'), ('INVENTARIO', 'Inventario'), ('VENTAS', 'Ventas'), ('TRANSFERENCIAS', 'Transferencias'), ('CLIENTES', 'Clientes'), ('REPORTES', 'Reportes'), ('USUARIOS', 'Usuarios'), ('CONFIGURACION', 'Configuración')], max_length=50, verbose_name='Módulo')),
                ('tipo_permiso', models.CharField(choices=[('VER', 'Ver/Listar'), ('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar'), ('EXPORTAR', 'Exportar'), ('IMPORTAR', 'Importar')], max_length=20, verbose_name='Tipo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'permiso',
                'unique_together': {('modulo', 'tipo_permiso')},
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('asignado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Asignado Por')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permiso_roles', to='autenticacion.permiso', verbose_name='Permiso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_permisos', to='autenticacion.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Rol Permiso',
                'verbose_name_plural': 'Roles Permisos',
                'db_table': 'rol_permiso',
                'unique_together': {('rol', 'permiso')},
            },
        ),
    ]
