# Generated by Django 4.2 on 2025-10-02 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_permiso_rolpermiso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre / Razón Social')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('tipo_proveedor', models.CharField(choices=[('DISTRIBUIDOR', 'Distribuidor'), ('FABRICANTE', 'Fabricante'), ('IMPORTADOR', 'Importador'), ('MAYORISTA', 'Mayorista'), ('MINORISTA', 'Minorista')], default='DISTRIBUIDOR', max_length=20, verbose_name='Tipo de Proveedor')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('pais', models.CharField(default='Bolivia', max_length=100, verbose_name='País')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('persona_contacto', models.CharField(blank=True, max_length=200, null=True, verbose_name='Persona de Contacto')),
                ('cargo_contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('condiciones_pago', models.CharField(default='Contado', max_length=100, verbose_name='Condiciones de Pago')),
                ('dias_credito', models.IntegerField(default=0, verbose_name='Días de Crédito')),
                ('calificacion', models.DecimalField(decimal_places=1, default=0.0, help_text='Calificación del proveedor', max_digits=3, verbose_name='Calificación (0-5)')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('PREMIUM', 'Premium'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('es_premium', models.BooleanField(default=False, verbose_name='Proveedor Premium')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('ODONTOLOGO', 'Odontólogo'), ('MEDICO', 'Médico'), ('EST_ODONTOLOGIA', 'Estudiante Odontología'), ('EST_MEDICINA', 'Estudiante Medicina'), ('EST_ENFERMERIA', 'Estudiante Enfermería'), ('EST_VETERINARIA', 'Estudiante Veterinaria'), ('ENFERMERO', 'Enfermero/a'), ('VETERINARIO', 'Veterinario/a'), ('LAB_DENTAL', 'Laboratorio Dental')], max_length=50, unique=True, verbose_name='Código')),
                ('nombre_tipo', models.CharField(max_length=100, verbose_name='Nombre del Tipo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Tipo de Cliente',
                'verbose_name_plural': 'Tipos de Cliente',
                'db_table': 'tipo_cliente',
                'ordering': ['nombre_tipo'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(blank=True, help_text='Para clínicas, laboratorios o empresas', max_length=200, null=True, verbose_name='Razón Social')),
                ('nit', models.CharField(blank=True, help_text='Para facturación', max_length=20, null=True, unique=True, verbose_name='NIT')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('especialidad', models.CharField(blank=True, max_length=200, null=True, verbose_name='Especialidad')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('VIP', 'VIP'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('es_vip', models.BooleanField(default=False, verbose_name='Cliente VIP')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Límite de Crédito (Bs.)')),
                ('descuento_especial', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de descuento adicional', max_digits=5, verbose_name='Descuento Especial (%)')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('tipo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='autenticacion.tipocliente', verbose_name='Tipo de Cliente')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
