# Generated by Django 4.2 on 2025-10-03 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_proveedor_tipocliente_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['razon_social'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='descuento_especial',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='es_vip',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='limite_credito',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='cargo_contacto',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='condiciones_pago',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='dias_credito',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='es_premium',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='persona_contacto',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='telefono',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor', to='autenticacion.persona', verbose_name='Persona'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipo_proveedor',
            field=models.CharField(choices=[('DISTRIBUIDOR', 'Distribuidor'), ('FABRICANTE', 'Fabricante'), ('IMPORTADOR', 'Importador')], default='DISTRIBUIDOR', max_length=20, verbose_name='Tipo de Proveedor'),
        ),
    ]
