# Generated by Django 4.2 on 2025-10-03 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0004_alter_proveedor_options_remove_cliente_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proveedor', to='autenticacion.persona', verbose_name='Persona'),
        ),
    ]
